-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "currency" SET DEFAULT 'GBP',
ALTER COLUMN "start_date" SET DATA TYPE DATE,
ALTER COLUMN "end_date" SET DATA TYPE DATE,
ALTER COLUMN "billing_period" SET DEFAULT 'MONTHLY',
ALTER COLUMN "next_payment_date" SET DATA TYPE DATE,
ALTER COLUMN "status" SET DEFAULT 'ACTIVE';
